// Copyright (c) Microsoft Corporation.
// Licensed under the MIT license.

package client

import (
	"fmt"
	"os"
	"strings"
	"sync"
	"time"

	admin_pb "github.com/microsoft/moc/rpc/common/admin"
	compute_pb "github.com/microsoft/moc/rpc/mochostagent/compute"
	security_pb "github.com/microsoft/moc/rpc/mochostagent/security"
	"github.com/spf13/viper"
	"go.opencensus.io/plugin/ocgrpc"
	"google.golang.org/grpc"
	"google.golang.org/grpc/keepalive"
	log "k8s.io/klog"

	"github.com/microsoft/moc/pkg/auth"
)

const (
	debugModeTLS        = "WSSD_DEBUG_MODE"
	KnownServerPort     = 48000
	KnownAuthServerPort = 48001
)

var (
	mux             sync.Mutex
	connectionCache map[string]*grpc.ClientConn
)

func init() {
	connectionCache = map[string]*grpc.ClientConn{}
}

// Returns nil if debug mode is on; err if it is not
func isDebugMode() error {
	debugEnv := strings.ToLower(os.Getenv(debugModeTLS))
	if debugEnv == "on" {
		return nil
	}
	if viper.GetBool("Debug") {
		return nil
	}
	return fmt.Errorf("Debug Mode not set")
}

func getDefaultServerEndpoint(serverAddress *string) string {
	return fmt.Sprintf("%s:%d", *serverAddress, KnownServerPort)
}

func getDefaultAuthServerEndpoint(serverAddress *string) string {
	return fmt.Sprintf("%s:%d", *serverAddress, KnownAuthServerPort)
}

// This is a hack to get around changing a bunch of files for code that will eventually be autogenerated
// the assumption we make is that if we find ":" in the server address we assume the port is there already
func getServerEndpoint(serverAddress *string) string {
	if !strings.Contains(*serverAddress, ":") {
		return getDefaultServerEndpoint(serverAddress)
	}
	return *serverAddress
}

func getAuthServerEndpoint(serverAddress *string) string {
	if !strings.Contains(*serverAddress, ":") {
		return getDefaultAuthServerEndpoint(serverAddress)
	}
	return *serverAddress
}

func getDefaultDialOption(authorizer auth.Authorizer) []grpc.DialOption {
	var opts []grpc.DialOption

	// Debug Mode allows us to talk to mochostagent without a proper handshake
	// This means we can debug and test mochostagent without generating certs
	// and having proper tokens
	// Check if debug mode is on
	if ok := isDebugMode(); ok == nil {
		opts = append(opts, grpc.WithInsecure())
	} else {
		opts = append(opts, grpc.WithTransportCredentials(authorizer.WithTransportAuthorization()))
	}

	opts = append(opts, grpc.WithKeepaliveParams(
		keepalive.ClientParameters{
			Time:                1 * time.Minute,
			Timeout:             20 * time.Second,
			PermitWithoutStream: true,
		}))

	opts = append(opts, grpc.WithStatsHandler(&ocgrpc.ClientHandler{}))
	return opts
}

func getClientConnection(serverAddress *string, authorizer auth.Authorizer) (*grpc.ClientConn, error) {
	mux.Lock()
	defer mux.Unlock()
	endpoint := getServerEndpoint(serverAddress)

	conn, ok := connectionCache[endpoint]
	if ok {
		return conn, nil
	}

	opts := getDefaultDialOption(authorizer)
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return nil, err
	}

	connectionCache[endpoint] = conn

	return conn, nil
}

// CloseClientConnectionByEndpoint allows a caller to close the current clientconn
// for a particular endpoint
func CloseClientConnectionByEndpoint(serverAddress *string) error {
	mux.Lock()
	defer mux.Unlock()
	endpoint := getServerEndpoint(serverAddress)

	conn, ok := connectionCache[endpoint]
	if ok {
		err := conn.Close()
		if err != nil {
			return err
		}

		delete(connectionCache, endpoint)
	}
	return nil
}

// GetVirtualMachineClient returns the virtual machine client to comminicate with the mochostagent
func GetVirtualMachineClient(serverAddress *string, authorizer auth.Authorizer) (compute_pb.VirtualMachineAgentClient, error) {
	conn, err := getClientConnection(serverAddress, authorizer)
	if err != nil {
		log.Fatalf("Unable to get VirtualMachineClient. Failed to dial: %v", err)
	}

	return compute_pb.NewVirtualMachineAgentClient(conn), nil
}

// GetLogClient returns the log client to communicate with the mochostagent
func GetLogClient(serverAddress *string, authorizer auth.Authorizer) (admin_pb.LogAgentClient, error) {
	conn, err := getClientConnection(serverAddress, authorizer)
	if err != nil {
		log.Fatalf("Unable to get LogClient. Failed to dial: %v", err)
	}

	return admin_pb.NewLogAgentClient(conn), nil
}

// GetDebugClient returns the log client to communicate with the mochostagent
func GetDebugClient(serverAddress *string, authorizer auth.Authorizer) (admin_pb.DebugAgentClient, error) {
	conn, err := getClientConnection(serverAddress, authorizer)
	if err != nil {
		log.Fatalf("Unable to get DebugClient. Failed to dial: %v", err)
	}

	return admin_pb.NewDebugAgentClient(conn), nil
}

// GetKeyVaultClient returns the keyvault client to communicate with the mochostagent
func GetKeyVaultClient(serverAddress *string, authorizer auth.Authorizer) (security_pb.KeyVaultAgentClient, error) {
	conn, err := getClientConnection(serverAddress, authorizer)
	if err != nil {
		log.Fatalf("Unable to get KeyVaultClient. Failed to dial: %v", err)
	}

	return security_pb.NewKeyVaultAgentClient(conn), nil
}

// GetSecretClient returns the secret client to communicate with the mochostagent
func GetSecretClient(serverAddress *string, authorizer auth.Authorizer) (security_pb.SecretAgentClient, error) {
	conn, err := getClientConnection(serverAddress, authorizer)
	if err != nil {
		log.Fatalf("Unable to get KeyVaultClient. Failed to dial: %v", err)
	}

	return security_pb.NewSecretAgentClient(conn), nil
}

// GetIdentityClient returns the secret client to communicate with the mochostagent
func GetIdentityClient(serverAddress *string, authorizer auth.Authorizer) (security_pb.IdentityAgentClient, error) {
	conn, err := getClientConnection(serverAddress, authorizer)
	if err != nil {
		log.Fatalf("Unable to get IdentityClient. Failed to dial: %v", err)
	}

	return security_pb.NewIdentityAgentClient(conn), nil
}

// GetCertificateClient returns the secret client to communicate with the mochostagent
func GetCertificateClient(serverAddress *string, authorizer auth.Authorizer) (security_pb.CertificateAgentClient, error) {
	conn, err := getClientConnection(serverAddress, authorizer)
	if err != nil {
		log.Fatalf("Unable to get CertificateClient. Failed to dial: %v", err)
	}

	return security_pb.NewCertificateAgentClient(conn), nil
}

// GetAuthenticationClient returns the secret client to communicate with the mochostagent
func GetAuthenticationClient(serverAddress *string, authorizer auth.Authorizer) (security_pb.AuthenticationAgentClient, error) {

	var opts []grpc.DialOption
	opts = append(opts, grpc.WithTransportCredentials(authorizer.WithTransportAuthorization()))
	opts = append(opts, grpc.WithPerRPCCredentials(authorizer.WithRPCAuthorization()))
	opts = append(opts, grpc.WithStatsHandler(&ocgrpc.ClientHandler{}))
	conn, err := grpc.Dial(getAuthServerEndpoint(serverAddress), opts...)
	if err != nil {
		log.Fatalf("Unable to get AuthenticationClient. Failed to dial: %v", err)
	}

	return security_pb.NewAuthenticationAgentClient(conn), nil
}
